export const projects = [
  {
    title: 'Adsaffairs',
    category: 'Digital Marketing',
    type: 'Digital Marketing & Growth Agency',
    image: '/projects/adsaffairs.png',
    description: 'A premium digital growth platform focused on creative branding, performance marketing, lead generation, and scalable digital solutions.',
    stack: ['React', 'Tailwind CSS', 'JavaScript', 'Digital Marketing'],
    live: 'https://adsaffairs.com',
  },
  {
    title: 'ContactCalls',
    category: 'Web Development',
    type: 'Communication & Call Center Solutions',
    image: '/projects/contactcalls.png',
    description: 'A professional business communication platform providing customer support, call center, lead generation, and multi-channel communication solutions.',
    stack: ['React', 'Tailwind CSS', 'JavaScript', 'Responsive UI'],
    live: 'https://www.contactcalls.com',
  },
  {
    title: 'MilkRecord',
    category: 'SaaS & Digital Products',
    type: 'Dairy Operations & Management Platform',
    image: 'https://milkrecord.in/logo.png',
    imageFit: 'contain',
    description: 'A dairy management platform for collection centers, retail counters, and processing plants, covering farmer records, milk collection and payout ledgers, POS billing, and RMRD operations.',
    stack: ['Milk Collection', 'Dairy POS', 'Farmer Ledger', 'Plant RMRD'],
    live: 'https://milkrecord.in',
  },
  {
    title: 'ExpertAd',
    category: 'Digital Marketing',
    type: 'Performance Marketing Platform',
    image: '/projects/expertad.png',
    description: 'A performance-driven advertising platform built around affiliate marketing, lead generation, media buying, analytics, and growth solutions.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'Performance Marketing'],
    live: 'https://www.expertad.co.in',
  },
  {
    title: 'KSR Realty Ventures',
    category: 'Web Development',
    type: 'Real Estate & Property Development',
    image: '/projects/ksrrealty.png',
    description: 'A premium real estate platform showcasing property development, residential projects, luxury homes, and real estate investment opportunities.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'Real Estate'],
    live: 'https://www.ksrrealtyventures.in',
  },
  {
    title: 'FortuneAdsLLC',
    category: 'Digital Marketing',
    type: 'Performance Marketing & Lead Generation',
    image: '/projects/fortuneadsllc.png',
    description: 'A premium performance marketing platform built to connect advertisers and publishers through high-intent consumer acquisition. The platform focuses on measurable campaigns, quality leads, calls, clicks, and scalable digital growth.',
    stack: ['React', 'Vite', 'JavaScript', 'Responsive Design', 'Vercel'],
    live: 'https://fortuneadslcc.vercel.app/',
  },
  {
    title: 'Covian Hotels & Resorts',
    category: 'UI/UX & Digital Products',
    type: 'Luxury Hospitality & Digital Booking Experience',
    image: '/projects/covianhotels.png',
    description: 'A luxury hospitality website crafted to showcase premium hotels and resorts through immersive visuals, destination discovery, refined user experience, and an integrated booking journey.',
    stack: ['React', 'Vite', 'JavaScript', 'Modern UI/UX', 'Responsive Design', 'Vercel'],
    live: 'https://covianhotels.vercel.app/',
  },

  {
    title: 'KSR Realty Venture',
    category: 'Digital Products',
    type: 'Real Estate Platform & Property Management',
    image: '/projects/KSR.png',
    description: 'A full-stack real estate platform built to help users discover properties, submit property listings, and explore real estate services through a premium, responsive digital experience. The platform includes Supabase-powered property data, customer property submissions, admin verification and management, property search, service pages, EMI calculator, blogs, and SEO-ready pages.',
    stack: [
      'React',
      'JavaScript',
      'Vite',
      'React Router',
      'Supabase',
      'PostgreSQL',
      'Responsive Design',
      'Vercel'
    ],
    live: 'https://ksrrealtyventure.com/',
  },
];
